version: '3'
services:
  postgres:
    container_name: abe_pg
    image: agilelabs/gia-pg:main
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=azdev
      - POSTGRES_PASSWORD=password
      - PGDATA=azdev-data